spring:
  application:
    name: oatuh2-example
  server:
    port: 8080

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database: h2
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect

  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB

  sql:
    init:
      mode: ALWAYS
      platform: h2
      schema-locations: classpath:./sql/schema_new.sql, classpath:org/springframework/security/oauth2/client/oauth2-client-schema.sql
#      data-locations: classpath:./sql/data_new.sql
      encoding: UTF-8

  jwt:
    header: token
    issuer: prgrms
    client-secret: EENY5W0eegTf1naQB2eDeyCLl5kRS2b8xa5c4qLdS0hmVjtbvo8tOyhPMcAmtPuQ
    expiry-seconds: 60

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: 09d33f90f2b35207ef5b4c3549029620 # ?????? >> rest api ?
            client-secret: Fep4PfVurayscrOk3XCME1Y8r0rbKOYr # ?? client-secret
            scope: profile_nickname, profile_image # ???? ?? ?? ?? ,? ???? ??
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}" # ?????? redirect_url ?? ??? ????
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        provider:
          kakao: # kakao docu ??  ?? >> ??? ??? >> RestAPI >> ???? ??
            authorization-uri: https://kauth.kakao.com/oauth/authorize # ?? >> ??? ??? >> RestAPI >> ??? ?? ??? ??? ???? ?? 1?? ????? ???? API
            token-uri: https://kauth.kakao.com/oauth/token # ?? >> ??? ??? >> RestAPI >> ?? ??  1?? ???? ???? ?? ?? ??
            user-info-uri: https://kapi.kakao.com/v2/user/me # ?? >> ??? ??? >> RestAPI >> ??? ?? ????
            user-name-attribute: id # ?? >> ??? ??? >> RestAPI >> ??? ?? ?????? ?? ??? ?? ??? ?? ?? ?? id?? ???? ??.
