spring:
  application:
    name: oatuh2-example
  server:
    port: 8080

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database: h2
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect

  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB

  sql:
    init:
      mode: ALWAYS
      platform: h2
      schema-locations: classpath:./sql/schema_new.sql, classpath:org/springframework/security/oauth2/client/oauth2-client-schema.sql
#      data-locations: classpath:./sql/data_new.sql
      encoding: UTF-8

  jwt:
    header: token
    issuer: prgrms
    client-secret: ${JWT_SECRET:ENC(Iyl8A3kGYEGqa8nLZik+xEAJ1ITjb49F)}
    expiry-seconds: 60

  security:
    oauth2:
      client:
        registration:
          kakao: # https://developers.kakao.com/ >> 상단 메뉴 내 애플리케이션
            client-name: kakao
            client-id: ${K_CLIENT_ID:ENC(DzeX9QvHWlYp+zZ8p4x2DwnqY9GSANGejlb8OFDFZGbL7PdYerVpu7GCoc3hYlNB)} # >> 요약정보 >> 앱키 >> REST API키
            client-secret: ${K_CLIENT_SECRET:ENC(LsVgYWdJE1MUPX4tYZz4Z8/aw4FO0ynxhL4VXnuYne2kfDLGtEV79jSiDMSK84vT)} # 보안 >> client-secret 코드
            scope: ${K_SCOPE:ENC(j2ly2z6/SWRuTSDEVEHSPgTGsA5fP7kBacGhK1X7rXInBS4mza7UTg==)} # 동의항목 >> 개인정보 별 id 입력 ','로 구분
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}" # 카카오로그인 >>  redirect_url - 마지막은 변수처리 해야함(시큐리티 내부에서는 변수로 oauth provider, registration 정보를 가져옴)
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        provider:  # https://developers.kakao.com/ >> 상단 메뉴에 문서 클릭
          kakao: # 왼쪽 메뉴 카카오 로그인 >> REST API 클릭
            authorization-uri: https://kauth.kakao.com/oauth/authorize # 인가코드 받기 부분 GET /oauth/authorize [1회성 코드를 받는  API]
            token-uri: https://kauth.kakao.com/oauth/token # 토큰 받기 POST /oauth/token HTTP/1.1 [엑세스 토큰을 받기위한 uri]
            user-info-uri: https://kapi.kakao.com/v2/user/me # 사용자 정보 가져오기 부분
            user-name-attribute: id #사용자 고유 식별키를 추출하기 위한 필드명 ( 필수라고 나와있음) | 사용자 정보 가져오기 부분에 응답 모델을 보면

encryptor:
  key: oauth2