spring:
  application:
    name: 'batch-tutoral'
  sql:
    init:
      schema-locations: classpath:batch-schema-h2.sql
      mode: always

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2-console

feign:
  client:
    config:
      default:
        decoder:
          xml:
            enabled: true
public-data:
  api:
    serviceKey: ${SERVICE_KEY}

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    org.springframework.batch: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.support: DEBUG
