spring:
  application:
    name: security-practice
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: spring.datasource.driverClassName=org.h2.Driver
        show_sql: true
        ddl-auto: create
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
jwt:
  token:
    header: security-test
    issuer: whywhale
    client-secret: test
    expiry-seconds: 1

secret:
  encoder:
    secret: mgNtjb7wT83J9YVdo4THhSJbmqWgfFHbHZu4OPdgGZfX6KacoPrrXlTsX5m3dZBukJptpnvSiwqY0hzV
