spring:
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
      username: sa
      password:
      driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
          format_sql: spring.datasource.driverClassName=org.h2.Driver
          show_sql: true
          ddl-auto: create
      show-sql: true
      generate-ddl: true
      defer-datasource-initialization: true
jwt:
  token:
    access-header: ${JWT_ACCESS_HEADER:ENC(wCDnLXsQpxmETxULplUl/FQK040NhP50)}
    refresh-header: ${JWT_REFRESH_HEADER:ENC(7w2hCckNkFDU0fhPsHYPVPRgQIP5F8D2xCSZ1WSqOl0=)}
    issuer: ${JWT_ISSUER:ENC(2a4b4nIfQ71azDnMx//jIOG2nZT+xbGIYzNUwI807aM=)}
    client-secret: ${JWT_SECRET:ENC(OoBtxYPhAJ0MlixnVsTUD1rMxvsU+csy)}
    access-expiry-seconds: 1
    refresh-expiry-seconds: 5

encryptor:
  key: ${ENCRYPTOR_KEY:around-the-korea}