spring:
  application:
    name: 'elastic tutorial'
    main.allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/tutorial
    username: whywhale
    password: whywhale
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        search:
          backend:
            type: elasticsearch
            hosts: http://localhost:9200
            index_defaults:
              schema_management: strategy=CREATE


  elasticsearch:
    uris: http://localhost:9200

