server:
  port: ${PORT_NUMBER:8080}

grpc:
  server: ### grpc 충돌을 피하기 위한 안그러면 gradle 의존성에서 grpc-server 제거해야함
    port: 3333
  client:
    calculatorService:
      address: static://localhost:${GRPC_SERVER_PORT:9090}
      negotiationType: plaintext