server:
  port: ${PORT_NUMBER:8081}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9090}

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.boot.autoconfigure: INFO
    io.grpc: DEBUG
    net.devh.boot.grpc: DEBUG
    org.springframework.context.annotation: DEBUG